trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - script: ls -al && pwd
    displayName: 'List Files & Current working directory'

  - script: echo "The Build Id is $(Build.BuildId) with Build Number is $(Build.BuildNumber) and War is located at $(Build.ArtifactStagingDirectory)"
    displayName: 'Printing the Build Id and Number'

  - script: sudo apt update >> /dev/null 2>&1 && sudo apt install openjdk-8-jdk >> /dev/null 2>&1 && java -version
    displayName: 'Installing the java 8 and checking the version'

  - script: ls -al && chmod 700 build.sh && sudo bash ./build.sh && ls -al
    displayName: 'Run the build script..'

  # - script: sudo apt update && sudo apt install openjdk-8-jdk && java -version
  #   displayName: 'Installing the java 8 and checking the version'