trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - script: ls -al && pwd
    displayName: 'List Files & Current working directory'

  - script: echo "The Build Id is $(Build.BuildId) with Build Number is $(Build.BuildNumber) and War is located at $(Build.ArtifactStagingDirectory)"
    displayName: 'Printing the Build Id and Number'

  - script: sudo apt update >> /dev/null 2>&1 && sudo apt install openjdk-8-jdk >> /dev/null 2>&1 && java -version
    displayName: 'Installing the java 8 and checking the version'

  - script: ls -al && chmod 700 build.sh && sudo bash ./build.sh && ls -al
    displayName: 'Run the build script..'

  # - script: sudo apt update && sudo apt install openjdk-8-jdk && java -version
  #   displayName: 'Installing the java 8 and checking the version'

  - script: ls -al && mv ROOT.war ROOT$(Build.BuildId).war && ls -al
    displayName: 'List Files & Rename ROOT.war'

  
  - task: CopyFiles@2
    inputs:
      Contents: 'ROOT$(Build.BuildId).war'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      OverWrite: true
  
  - script: ls -al $(Build.ArtifactStagingDirectory)
    displayName: 'List Files Build Artifact Staging directory'
    
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ROOT$(Build.BuildId).war'
      publishLocation: 'Container'
  
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-azurede-connection'
      regionName: 'ap-northeast-1'
      bucketName: 'aws-azuredevops'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      globExpressions: 'ROOT$(Build.BuildId).war'
      storageClass: 'REDUCED_REDUNDANCY'